[package]
name = "leanquery"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
bindgen = { version = "0.71.1", default-features = true }
cc = { version = "1.2.18", features = ["parallel"] }